In [ ]:
import numpy as np

x = np.array([1, 2, 3])

print(x.shape, x.ndim)

W = np.array([[1, 2, 3], [4, 5, 6]])

print(W.shape, W.ndim)

(3,) 1
(2, 3) 2


In [ ]:
import numpy as np

W1 = np.random.rand(2, 4)
b1 = np.random.rand(4)
x = np.random.rand(10, 2)

h = np.dot(x, W1) + b1
print(h)

[[1.0598651  1.509186   1.42935009 1.25937751]
 [0.67525812 1.0179225  0.72739366 0.81837777]
 [1.28377137 1.8404676  1.28197583 1.08929711]
 [0.83754353 1.22811447 0.98794279 0.97709871]
 [0.81052605 1.20595133 0.78702843 0.82974665]
 [0.95175289 1.38192529 1.09902061 1.0333125 ]
 [1.15154543 1.65495185 1.24474593 1.09435272]
 [0.87093998 1.28126148 0.92009792 0.91652523]
 [1.0306179  1.5009047  1.01894031 0.95178131]
 [1.34935453 1.91900092 1.4659772  1.21385677]]


In [ ]:
import utils
import numpy as np

W1 = np.random.rand(2, 4)
b1 = np.random.rand(4)
x = np.random.rand(10, 2)

W2 = np.random.rand(4, 3)
b2 = np.random.rand(3)

h = np.dot(x, W1) + b1
a = utils.sigmoid(h)
s = np.dot(a, W2) + b2

s


array([[1.72411632, 1.56490099, 1.11920644],
       [1.5754352 , 1.45324718, 1.00136681],
       [1.49892787, 1.41726218, 0.94889263],
       [1.66808049, 1.55424236, 1.08890262],
       [1.515755  , 1.42760253, 0.96154597],
       [1.5817887 , 1.51022829, 1.02928367],
       [1.54796572, 1.4551602 , 0.98907673],
       [1.72256044, 1.56328833, 1.11780091],
       [1.46836234, 1.40237381, 0.9275475 ],
       [1.70106653, 1.53701402, 1.09660411]])

## レイヤー分けしたクラスにforward()を実装し推論だけさせてみる。パラメーターは適当

In [ ]:
import utils
import numpy as np

class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I, H, O = input_size, hidden_size, output_size

    W1 = np.random.randn(I, H)
    b1 = np.random.randn(H)

    W2 = np.random.randn(H, O)
    b2 = np.random.randn(O)

    self.layers = [
      utils.Affine(W1, b1),
      utils.Sigmoid(),
      utils.Affine(W2, b2),
    ]

    self.params = []
    for layer in self.layers:
        self.params += layer.params


  def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

s

array([[ 1.16120368, -2.31174617, -0.67859734],
       [ 1.36293376, -2.35419301, -1.79386136],
       [ 1.06617206, -2.17832876, -0.69330937],
       [ 1.39162017, -2.54780939, -1.25760542],
       [ 1.02141566, -1.86145824, -1.87977576],
       [ 1.50282583, -2.74728079, -1.28966697],
       [ 0.51146292, -1.19068122, -1.46429699],
       [ 1.46065486, -2.63537312, -1.3578986 ],
       [ 1.45363474, -2.68234845, -1.12922591],
       [ 0.78729241, -1.78460497, -0.94897376]])

## Repeatノード

In [ ]:
import numpy as np

D,N = 8,7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0)

print(x,y)

[[ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]] [[ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]
 [ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]
 [ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]
 [ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]
 [ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]
 [ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]
 [ 0.37754813  0.51592248  1.12738884  1.42163482 -1.02147376 -1.08902651
   0.48254805  0.37253892]]


### スパイラルデータセットの表示

In [15]:
import os
from google.colab import drive
drive.mount('/content/drive')

# あなたのフォルダパス
target_dir = "/content/drive/MyDrive/colab/projects/learn/01章"

# 移動
os.chdir(target_dir)

import sys
sys.path.append('..')
from dataset import spiral


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


ModuleNotFoundError: No module named 'dataset'